[testing]
input_id = "https://drive.google.com/drive/folders/1asOCy56ySlAAf62oHWsEJXKghGrEPFKj?usp=drive_link"
ref_id = "https://drive.google.com/drive/folders/1O_7KuqkqENIeytR6NVVktH1Ul-Yo3hUo?usp=sharing"
output_id = "https://drive.google.com/drive/folders/1E2OcBK8DiYh_nIQd49Lc3ltL38J8d_CJ?usp=drive_link"

[google]
client_id = "577036192159-c9fcpkkqanhn5je28tf6acp062i3orj4.apps.googleusercontent.com"
client_secret = "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"
redirect_uris = ["https://eskwelabs-jd-automation.streamlit.app/"]
auth_uri = "https://accounts.google.com/o/oauth2/auth"
token_uri = "https://oauth2.googleapis.com/token"
project_id = "eskwelabs-jd-automation"
auth_provider_x509_cert_url = "https://www.googleapis.com/oauth2/v1/certs"
client_type = "web"